# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/tt/riscv/riscv.cache/wt [current_project]
set_property parent.project_path I:/tt/riscv/riscv.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo i:/tt/riscv/riscv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  I:/tt/common/block_ram/block_ram.v
  I:/tt/cpu.v
  I:/tt/defines.v
  I:/tt/ex.v
  I:/tt/ex_mem.v
  I:/tt/common/fifo/fifo.v
  I:/tt/hci.v
  I:/tt/id.v
  I:/tt/id_ex.v
  I:/tt/if_id.v
  I:/tt/inst_cache.v
  I:/tt/mem.v
  I:/tt/mem_wb.v
  I:/tt/memctrl.v
  I:/tt/pc_reg.v
  I:/tt/ram.v
  I:/tt/regfile.v
  I:/tt/stall_controller.v
  I:/tt/common/uart/uart.v
  I:/tt/common/uart/uart_baud_clk.v
  I:/tt/common/uart/uart_rx.v
  I:/tt/common/uart/uart_tx.v
  I:/tt/riscv_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc I:/tt/Basys-3-Master.xdc
set_property used_in_implementation false [get_files I:/tt/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
